apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiMnhsWnpBNE9EQTVOenBuYUhCZlZVRkdiRzh3ZFcxMlMzcFhWbGxFTjFNelVHNVplR0ZWWmxsbllWTk9Nazl5WWpacCIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
